server.port: 8090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 9836
    url: jdbc:mariadb://localhost:3306/board

  jpa:
    hibernate:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false